export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_CURRENT_DT = 'SET_CURRENT_DT';
export const CHOOSE_CURRENT_CLIENT_ACCOUNT = 'CHOOSE_CURRENT_CLIENT_ACCOUNT';

export const FIND_CLIENT = 'FIND_CLIENT';
export const FIND_AGENT = 'FIND_AGENT';

export const FIND_TASK = 'FIND_TASK';

export const FIND_CLIENT_CHECKBOOK = 'FIND_CLIENT_CHECKBOOK';
export const FIND_AGENT_CHECKBOOK = 'FIND_AGENT_CHECKBOOK';
export const CHOOSE_CURRENT_CLIENT_ACCOUNT_CHECKBOOK = 'CHOOSE_CURRENT_CLIENT_ACCOUNT_CHECKBOOK';
export const REGISTER_STATEMENT_CHECKBOOK = 'REGISTER_STATEMENT_CHECKBOOK';
export const GET_CHECKBOOK = 'GET_CHECKBOOK';
export const GET_COMISSION = 'GET_COMISSION';
export const GIVE_CHECKBOOK = 'GIVE_CHECKBOOK';
export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_TEST_POSTS = 'GET_TEST_POSTS';
export const ERROR_POSTFIX = "_REST_ERROR";
export const SUCCESS_POSTFIX = "_REST_SUCCESS";

export const LOAD_BEGIN = 'LOAD_BEGIN';

export const IDENTIFY_CARD_POS = 'IDENTIFY_CARD_POS';
export const SET_HAS_CASHING_OUT_FEATURES = 'SET_HAS_CASHING_OUT_FEATURES';
export const SET_WITHDRAWAL_SUM = 'SET_WITHDRAWAL_SUM';
export const ENTER_PIN = 'ENTER_PIN';
export const WITHDRAWAL_SEND_COMPLIENCE = 'WITHDRAWAL_SEND_COMPLIENCE';
export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT';
export const SET_SELECTED_AGENT = 'SET_SELECTED_AGENT';
export const SET_SELECTED_ACCOUNT = 'SET_SELECTED_ACCOUNT';
export const SET_SELECTED_OPERATION = 'SET_SELECTED_OPERATION';
export const UPDATE_CURRENT_OPERATION = 'UPDATE_CURRENT_OPERATION';
export const RESET_INFLOW_STATE = 'RESET_INFLOW_STATE';
export const RESET_CLIENTS_AGENTS_AND_ACCOUNTS_STATE = 'RESET_CLIENTS_AGENTS_AND_ACCOUNTS_STATE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_AGENTS = 'GET_AGENTS';

export const GET_CLIENTS_FOR_DEPOSIT = 'GET_CLIENTS_FOR_DEPOSIT';
export const GET_ACCOUNTS_FOR_DEPOSIT = 'GET_ACCOUNTS_FOR_DEPOSIT';
export const GET_AGENTS_FOR_DEPOSIT = 'GET_AGENTS_FOR_DEPOSIT';
export const GET_SYMBOLS = 'GET_SYMBOLS';
export const SEND_EVENT = 'SEND_EVENT';

export const CREATE_CHECKBOOK = 'CREATE_CHECKBOOK';
export const UPDATE_OPERATION_STATUS = 'UPDATE_OPERATION_STATUS';

export const GET_CALCULATE_COMMISSION_OPERATION_FOR_DEPOSIT = 'GET_CALCULATE_COMMISSION_OPERATION_FOR_DEPOSIT';

export const GET_COMMISSION = 'GET_COMMISSION';

export const GET_AUD_EVENT_TYPES = 'GET_AUD_EVENT_TYPES';
export const GET_AUD_EVENTS = 'GET_AUD_EVENTS';

export const GET_END_DEPOSIT_OPERATION = 'GET_END_DEPOSIT_OPERATION';
export const POST_CASH_IN_OPERATION_CREATE = 'POST_CASH_IN_OPERATION_CREATE';
export const POST_CASH_OUT_OPERATION_CREATE = 'POST_CASH_OUT_OPERATION_CREATE';
export const POST_OPERATIONS_CANCEL = 'POST_OPERATIONS_CANCEL';
export const POST_OPERATIONS_FINISH = 'POST_OPERATIONS_FINISH';

export const GET_OPERATIONS_BY_AGENT = 'GET_OPERATIONS_BY_AGENT';

export const GET_COMPLIANCE = 'GET_COMPLIANCE';
